# django-deployment.yaml

apiVersion: apps/v1
kind: Deployment
metadata:
  name: chat-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: chat-api
  template:
    metadata:
      labels:
        app: chat-api
    spec:
      containers:
      - name: django-app
        image: makeem/chat-api:v1
        ports:
        - containerPort: 8000
